name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest-image to run steps on
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
      pages: write
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-dotnet@v3.0.3
      - run: dotnet publish TigerGymWebUI/TigerGymWebUI.csproj -c Release -o release --nologo
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: $
          BASE_BRANCH: master
          BRANCH: github-pages
          FOLDER: release/wwwroot
          SINGLE_COMMIT: true
          
